# version: '3.9'

services:

  # ------------------------------------
  # PostgreSQL Database
  # ------------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: global_postgres15
    restart: always
    environment:
      POSTGRES_USER: sambila
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - sambilanet

  # ------------------------------------
  # MySQL Database
  # ------------------------------------
  mysql:
    image: mysql:8.0
    container_name: global_mysql8
    restart: always
    mem_limit: 2g
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sambilanet

  # ------------------------------------
  # phpMyAdmin (internal only)
  # ------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: global_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    networks:
      - sambilanet
    ports:
      - "127.0.0.1:8080:80"

  # ------------------------------------
  # Portainer (internal only)
  # ------------------------------------
  portainer:
    image: portainer/portainer-ce
    container_name: global_portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - sambilanet
    ports:
      - "127.0.0.1:9000:9000"

volumes:
  pg_data:
  mysql_data:
  portainer_data:

networks:
  sambilanet:
    external: true
